import logging
from d810.optimizers.flow.flattening.generic_dispatcher_unflattening_rule import GenericDispatcherUnflatteningRule
from d810.optimizers.flow.flattening.ollvm_dispatcher_collector import OllvmDispatcherCollector
from ida_hexrays import *

unflat_logger = logging.getLogger('D810.unflat')

class OllvmUnflattener(GenericDispatcherUnflatteningRule):
    DESCRIPTION = "Remove control flow flattening generated by OLLVM"
    DISPATCHER_COLLECTOR_CLASS = OllvmDispatcherCollector
    DEFAULT_UNFLATTENING_MATURITIES = [MMAT_CALLS, MMAT_GLBOPT1, MMAT_GLBOPT2]
    DEFAULT_MAX_DUPLICATION_PASSES = 20
    DEFAULT_MAX_PASSES = 5
